version: '3.8'

services:
  keycloak:
    image: jboss/keycloak
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: mariadb
      DB_ADDR: keycloak-db
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]

  keycloak-db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ./volume/keycloak/db/data:/var/lib/mysql

  wordpress:
    image: wordpress:6.2-php8.0-apache
    restart: always
    volumes:
      - ./volume/v1/wp:/var/www/html
      - ./apps/theme:/var/www/html/wp-content/themes/v1
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DEBUG: 1

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./volume/v1/db/data:/var/lib/mysql